sudo: required
dist: trusty
language: rust
addons:
  apt:
    packages:
      - libssl-dev
      - pkg-config
      - cmake
      - zlib1g-dev
rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      rustup component add clippy
    fi

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo build --features tfidf
  - cargo build --features textrank
  - cargo build --all-features
  - cargo test --all-features
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo clippy --all-features
    fi

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      cargo tarpaulin --all-features --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
