[package]
name = "jieba-capi"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
edition = "2018"

[dependencies]
jieba-rs = { version = "0.5", path = "../", features = ["textrank", "tfidf"] }
c_fixed_string = "0.2.0"

[lib]
crate-type = ["cdylib"]
