[package]
name = "weicheng"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
edition = "2018"

[dependencies]
jieba-rs = { path = "../.." }

[target.'cfg(unix)'.dependencies]
jemallocator = "0.3.2"
